# Generated by Django 2.2.1 on 2019-06-02 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_family', models.CharField(max_length=126)),
                ('iso_language_name', models.CharField(max_length=255)),
                ('native_name', models.CharField(max_length=255)),
                ('iso_639_1', models.CharField(max_length=8)),
                ('iso_639_2_t', models.CharField(max_length=8)),
                ('iso_639_2_b', models.CharField(max_length=8)),
                ('iso_639_3', models.CharField(max_length=8, null=True)),
                ('notes', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('screen_w', models.IntegerField()),
                ('screen_h', models.IntegerField()),
                ('aspect_ratio', models.CharField(max_length=16)),
                ('total_pixel_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('db_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('sub_file', models.FileField(upload_to='')),
                ('rate_good', models.IntegerField(default=0)),
                ('rate_bad', models.IntegerField(default=0)),
                ('release', models.DateField(null=True)),
                ('author', models.CharField(max_length=255)),
                ('downloaded', models.IntegerField(default=0)),
                ('comment', models.TextField(max_length=255, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subtitle.Language')),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subtitle.Resolution')),
                ('rip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subtitle.Rip')),
            ],
        ),
    ]
