# Generated by Django 2.2.1 on 2019-05-24 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ori_name', models.CharField(max_length=255)),
                ('iso', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('sub_file', models.FileField(upload_to='')),
                ('resolution', models.CharField(max_length=255)),
                ('rip', models.CharField(default='', max_length=255)),
                ('release', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('comment', models.TextField(max_length=255)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subtitle.language')),
            ],
        ),
    ]
