# Generated by Django 2.2.1 on 2019-07-19 01:13

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moviedb', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieSubtitleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('rate_good', models.IntegerField(default=0)),
                ('rate_bad', models.IntegerField(default=0)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('downloaded', models.IntegerField(default=0)),
                ('comment', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviedb.Language')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviedb.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TvSubtitleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('rate_good', models.IntegerField(default=0)),
                ('rate_bad', models.IntegerField(default=0)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('downloaded', models.IntegerField(default=0)),
                ('comment', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviedb.Language')),
                ('tv_episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviedb.TvEpisode')),
                ('tv_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviedb.TvSeason')),
                ('tv_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviedb.TvSeries')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TvSubtitles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subtitle.TvSubtitleInfo')),
            ],
        ),
        migrations.CreateModel(
            name='MovieSubtitles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subtitle.MovieSubtitleInfo')),
            ],
        ),
    ]
