# Generated by Django 2.2.1 on 2019-06-05 23:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitle', '0002_subtitle_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='notes',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='comment',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='user',
            field=models.IntegerField(),
        ),
    ]
