# Generated by Django 2.2.1 on 2019-06-07 00:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subtitle', '0003_auto_20190605_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtitle',
            name='author',
        ),
        migrations.RemoveField(
            model_name='subtitle',
            name='release',
        ),
        migrations.RemoveField(
            model_name='subtitle',
            name='resolution',
        ),
        migrations.RemoveField(
            model_name='subtitle',
            name='rip',
        ),
        migrations.AddField(
            model_name='subtitle',
            name='rate_star',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='run_time',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Resolution',
        ),
        migrations.DeleteModel(
            name='Rip',
        ),
    ]
