# Generated by Django 2.2.1 on 2019-06-09 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subtitle', '0004_auto_20190606_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
