# Generated by Django 2.2.1 on 2019-06-10 20:04

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subtitle', '0005_auto_20190609_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtitle',
            name='run_time',
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='comment',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
