# Generated by Django 2.2.1 on 2019-06-13 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitle', '0006_auto_20190610_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('iso_3166_2', models.CharField(max_length=8)),
                ('additional_aliases', models.CharField(max_length=128, null=True)),
            ],
        ),
    ]
