# Generated by Django 2.2.1 on 2019-06-18 23:13

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subtitle', '0007_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieSubtitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_created=True)),
                ('db_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('sub_file', models.FileField(upload_to='')),
                ('rate_star', models.IntegerField(default=0)),
                ('rate_good', models.IntegerField(default=0)),
                ('rate_bad', models.IntegerField(default=0)),
                ('downloaded', models.IntegerField(default=0)),
                ('comment', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subtitle.Language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TvSubtitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_created=True)),
                ('db_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('sub_file', models.FileField(upload_to='')),
                ('rate_star', models.IntegerField(default=0)),
                ('rate_good', models.IntegerField(default=0)),
                ('rate_bad', models.IntegerField(default=0)),
                ('downloaded', models.IntegerField(default=0)),
                ('comment', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subtitle.Language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Subtitle',
        ),
    ]
