# Generated by Django 2.2.1 on 2019-06-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitle', '0009_auto_20190619_0600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviesubtitle',
            options={'get_latest_by': ['upload_date'], 'ordering': ['-rate_good', '-downloaded']},
        ),
        migrations.AlterModelOptions(
            name='tvsubtitle',
            options={'get_latest_by': ['upload_date'], 'ordering': ['season_id', 'episode_id', 'rate_good', '-downloaded']},
        ),
        migrations.AlterField(
            model_name='tvsubtitle',
            name='sub_file',
            field=models.FileField(unique=True, upload_to=''),
        ),
        migrations.AddIndex(
            model_name='moviesubtitle',
            index=models.Index(fields=['title'], name='movie_title_idx'),
        ),
        migrations.AddIndex(
            model_name='tvsubtitle',
            index=models.Index(fields=['name'], name='tv_name_idx'),
        ),
    ]
