# Generated by Django 2.2.1 on 2019-06-24 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20190620_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedb',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tvseriesdb',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
