# Generated by Django 2.2.1 on 2019-06-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20190624_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedb',
            name='backdrop_path',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moviedb',
            name='poster_path',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
