# Generated by Django 2.2.1 on 2019-07-17 09:49

from django.db import migrations, models
import django.db.models.deletion
import moviedb.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification', models.CharField(max_length=6)),
                ('meaning', models.TextField()),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', null=True)),
                ('headquarters', models.CharField(default='', max_length=255)),
                ('homepage', models.URLField(null=True)),
                ('logo_path', models.CharField(max_length=64, null=True)),
                ('name', models.CharField(default='', max_length=1024)),
            ],
            bases=(models.Model, moviedb.models.TmdbInitMixin),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_3166_1', models.CharField(max_length=2, unique=True)),
                ('english_name', models.CharField(max_length=16)),
            ],
            bases=(models.Model, moviedb.models.TmdbInitMixin),
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            bases=(models.Model, moviedb.models.TmdbInitMixin),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_639_1', models.CharField(max_length=64, unique=True)),
                ('english_name', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult', models.BooleanField(default=False)),
                ('backdrop_path', models.CharField(default='', max_length=128, null=True)),
                ('budget', models.BigIntegerField(default=0)),
                ('homepage', models.URLField(max_length=2048, null=True)),
                ('imdb_id', models.CharField(max_length=16, null=True)),
                ('original_language', models.CharField(default='', max_length=4)),
                ('original_title', models.CharField(default='', max_length=1024)),
                ('overview', models.TextField(null=True)),
                ('popularity', models.FloatField(default=0)),
                ('poster_path', models.CharField(max_length=128, null=True)),
                ('release_date', models.DateField(null=True)),
                ('revenue', models.BigIntegerField(default=0)),
                ('runtime', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('Rumored', 'Rumored'), ('Planned', 'Planned'), ('InProduction', 'In Production'), ('PostProduction', 'Post Production'), ('Released', 'Released'), ('Canceled', 'Canceled')], default='', max_length=32)),
                ('tagline', models.CharField(max_length=1024, null=True)),
                ('title', models.CharField(default='', max_length=1024)),
                ('video', models.BooleanField(default=False)),
                ('vote_average', models.FloatField(default=0)),
                ('vote_count', models.IntegerField(default=0)),
                ('genres', models.ManyToManyField(related_name='_movie_genres_+', to='moviedb.Genre')),
                ('production_companies', models.ManyToManyField(related_name='_movie_production_companies_+', to='moviedb.Company')),
                ('production_countries', models.ManyToManyField(related_name='_movie_production_countries_+', to='moviedb.Country')),
                ('spoken_languages', models.ManyToManyField(related_name='_movie_spoken_languages_+', to='moviedb.Language')),
            ],
            bases=(models.Model, moviedb.models.TmdbInitMixin),
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headquarters', models.CharField(max_length=1024)),
                ('homepage', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=2048)),
                ('origin_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moviedb.Country')),
            ],
            bases=(models.Model, moviedb.models.TmdbInitMixin),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(null=True)),
                ('known_for_department', models.CharField(max_length=32)),
                ('deathday', models.DateField(null=True)),
                ('name', models.CharField(max_length=32)),
                ('also_known_as', models.CharField(max_length=2048)),
                ('gender', models.IntegerField(default=0)),
                ('biography', models.TextField()),
                ('popularity', models.FloatField(default=0)),
                ('place_of_birth', models.CharField(max_length=64, null=True)),
                ('profile_path', models.CharField(max_length=64, null=True)),
                ('adult', models.BooleanField(default=False)),
                ('imdb_id', models.CharField(max_length=16)),
                ('homepage', models.URLField(null=True)),
            ],
            bases=(models.Model, moviedb.models.TmdbInitMixin),
        ),
        migrations.CreateModel(
            name='PrimaryTranslations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='TvEpisode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_date', models.DateField(null=True)),
                ('episode_number', models.IntegerField(default=0)),
                ('name', models.CharField(default='no_name', max_length=2024)),
                ('overview', models.TextField(blank=True, null=True)),
                ('production_code', models.CharField(max_length=128, null=True)),
                ('season_number', models.IntegerField(default=0)),
                ('still_path', models.CharField(max_length=64, null=True)),
                ('vote_average', models.FloatField(default=0)),
                ('vote_count', models.IntegerField(default=0)),
                ('crew', models.ManyToManyField(related_name='_tvepisode_crew_+', to='moviedb.Person')),
                ('guest_stars', models.ManyToManyField(related_name='_tvepisode_guest_stars_+', to='moviedb.Person')),
            ],
            bases=(models.Model, moviedb.models.TmdbInitMixin),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=32)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviedb.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('size', models.IntegerField(choices=[('360', '360'), ('480', '480'), ('720', '720'), ('1080', '1080')])),
                ('type', models.CharField(max_length=16)),
                ('iso_3166_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviedb.Country')),
                ('iso_639_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviedb.Language')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviedb.Movie')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviedb.Site')),
            ],
        ),
        migrations.CreateModel(
            name='TvSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(default='', max_length=32)),
                ('air_date', models.DateField(null=True)),
                ('name', models.CharField(default='', max_length=1024)),
                ('overview', models.TextField(blank=True, null=True)),
                ('season_number', models.IntegerField(default=0)),
                ('episodes', models.ManyToManyField(to='moviedb.TvEpisode')),
            ],
            bases=(models.Model, moviedb.models.TmdbInitMixin),
        ),
        migrations.CreateModel(
            name='TVCertifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certifications', models.ManyToManyField(to='moviedb.Certifications')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviedb.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Tv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backdrop_path', models.CharField(max_length=64, null=True)),
                ('episode_run_time', models.CharField(default='', max_length=514)),
                ('first_air_date', models.DateField(null=True)),
                ('homepage', models.URLField(null=True)),
                ('in_production', models.BooleanField(default=False)),
                ('last_air_date', models.DateField(null=True)),
                ('name', models.CharField(default='', max_length=1024)),
                ('number_of_episodes', models.IntegerField(default=0)),
                ('number_of_seasons', models.IntegerField(default=0)),
                ('origin_country', models.CharField(max_length=512)),
                ('original_name', models.CharField(default='', max_length=1024)),
                ('overview', models.TextField(null=True)),
                ('popularity', models.FloatField(default=0)),
                ('poster_path', models.CharField(max_length=64, null=True)),
                ('status', models.CharField(default='', max_length=16)),
                ('type', models.CharField(default='', max_length=16)),
                ('vote_average', models.FloatField(default=0)),
                ('vote_count', models.IntegerField(default=0)),
                ('created_by', models.ManyToManyField(to='moviedb.Person')),
                ('genres', models.ManyToManyField(to='moviedb.Genre')),
                ('languages', models.ManyToManyField(related_name='_tv_languages_+', to='moviedb.Language')),
                ('last_episode_to_air', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_episode_to_air+', to='moviedb.TvEpisode')),
                ('networks', models.ManyToManyField(to='moviedb.Network')),
                ('next_episode_to_air', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_episode_to_air+', to='moviedb.TvEpisode')),
                ('original_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moviedb.Language')),
                ('production_companies', models.ManyToManyField(related_name='_tv_production_companies_+', to='moviedb.Company')),
                ('seasons', models.ManyToManyField(to='moviedb.TvSeason')),
            ],
            bases=(models.Model, moviedb.models.TmdbInitMixin),
        ),
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_3166_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviedb.Country')),
                ('zones', models.ManyToManyField(to='moviedb.Zone')),
            ],
        ),
        migrations.CreateModel(
            name='MovieCertifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certifications', models.ManyToManyField(to='moviedb.Certifications')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviedb.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=32)),
                ('jobs', models.ManyToManyField(to='moviedb.Job')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=9, null=True)),
                ('facebook_id', models.CharField(max_length=64, null=True)),
                ('instagram_id', models.CharField(max_length=64, null=True)),
                ('twitter_id', models.CharField(max_length=64, null=True)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviedb.Movie')),
                ('tv_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviedb.Tv')),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast', models.ManyToManyField(related_name='_credit_cast_+', to='moviedb.Person')),
                ('crew', models.ManyToManyField(related_name='_credit_crew_+', to='moviedb.Person')),
                ('movie_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moviedb.Movie')),
                ('tv_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moviedb.Tv')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='origin_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moviedb.Country'),
        ),
        migrations.AddField(
            model_name='company',
            name='parent_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moviedb.Company'),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('overview', models.TextField()),
                ('poster_path', models.CharField(max_length=255, null=True)),
                ('backdrop_path', models.CharField(max_length=255, null=True)),
                ('parts', models.ManyToManyField(to='moviedb.Movie')),
            ],
            bases=(models.Model, moviedb.models.TmdbInitMixin),
        ),
    ]
