# Generated by Django 2.2.1 on 2019-07-19 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='keyword',
            field=models.ManyToManyField(related_name='_movie_keyword_+', to='moviedb.Keyword'),
        ),
    ]
