# Generated by Django 2.2.1 on 2019-07-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0002_auto_20190718_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(default='unknown', max_length=1024),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='unknown', max_length=1024),
        ),
        migrations.AlterField(
            model_name='country',
            name='english_name',
            field=models.CharField(default='unknown', max_length=16),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(default='unknown', max_length=32),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(default='unknown', max_length=64),
        ),
        migrations.AlterField(
            model_name='movie',
            name='original_title',
            field=models.CharField(default='No Original Title', max_length=1024),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('Rumored', 'Rumored'), ('Planned', 'Planned'), ('InProduction', 'In Production'), ('PostProduction', 'Post Production'), ('Released', 'Released'), ('Canceled', 'Canceled')], default='Canceled', max_length=32),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tagline',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(default='unknown', max_length=1024),
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(default='unknown', max_length=2048),
        ),
        migrations.AlterField(
            model_name='person',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='known_for_department',
            field=models.CharField(default='unknown', max_length=32),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default='unknown', max_length=32),
        ),
        migrations.AlterField(
            model_name='tvepisode',
            name='name',
            field=models.CharField(default='unknown', max_length=2024),
        ),
        migrations.AlterField(
            model_name='tvseason',
            name='name',
            field=models.CharField(default='unknown', max_length=1024),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='name',
            field=models.CharField(default='unknown', max_length=1024),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='original_name',
            field=models.CharField(default='unknown', max_length=1024),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(default='unknown', max_length=128),
        ),
    ]
