# Generated by Django 2.2.1 on 2019-07-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0002_auto_20190709_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='media_type',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
