# Generated by Django 2.2.1 on 2019-07-11 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0003_auto_20190710_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='name',
        ),
    ]
