# Generated by Django 2.2.1 on 2019-07-20 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0003_auto_20190719_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='iso_3166_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moviedb.Country', to_field='iso_3166_1'),
        ),
        migrations.AlterField(
            model_name='video',
            name='iso_639_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moviedb.Language', to_field='iso_639_1'),
        ),
    ]
