# Generated by Django 2.2.1 on 2019-07-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0004_remove_language_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='name',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
