# Generated by Django 2.2.1 on 2019-07-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0006_auto_20190711_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
