# Generated by Django 2.2.1 on 2019-07-12 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0009_auto_20190711_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='origin_country',
            field=models.ForeignKey(db_column='iso_3166_1', on_delete=django.db.models.deletion.CASCADE, to='moviedb.Country', to_field='iso_3166_1'),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso_3166_1',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='iso_639_1',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
