# Generated by Django 2.2.1 on 2019-07-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0010_auto_20190712_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='popularity',
            field=models.FloatField(default=0),
        ),
    ]
