# Generated by Django 2.2.1 on 2019-07-12 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0012_remove_genre_media_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='_id',
        ),
    ]
