# Generated by Django 2.2.1 on 2019-07-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0013_remove_genre__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
