# Generated by Django 2.2.1 on 2019-07-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0015_auto_20190712_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
