# Generated by Django 2.2.1 on 2019-07-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0016_auto_20190712_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.RemoveField(
            model_name='company',
            name='parent_company',
        ),
        migrations.AddField(
            model_name='company',
            name='parent_company',
            field=models.ManyToManyField(null=True, related_name='_company_parent_company_+', to='moviedb.Company'),
        ),
    ]
