# Generated by Django 2.2.1 on 2019-07-12 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0017_auto_20190712_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='headquarters',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='company',
            name='origin_country',
            field=models.ForeignKey(db_column='iso_3166_1', null=True, on_delete=django.db.models.deletion.CASCADE, to='moviedb.Country', to_field='iso_3166_1'),
        ),
    ]
