# Generated by Django 2.2.1 on 2019-07-12 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0018_auto_20190712_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='origin_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moviedb.Country'),
        ),
    ]
