# Generated by Django 2.2.1 on 2019-07-12 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0019_auto_20190712_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='parent_company',
        ),
        migrations.AddField(
            model_name='company',
            name='parent_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moviedb.Company'),
        ),
    ]
